name: aman_liburan
description: Aman Liburan, this application helps the government to track the spread of Covid-19 from tourist attractions visited by the public, by implementing a computerized ticketing system and visitor data will be displayed live.
version: 0.0.1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_staggered_grid_view: ^0.3.0
  shared_preferences: ^0.5.7+3
  flutter_spinkit: ^4.1.2+1
  eva_icons_flutter: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  carousel_slider: ^2.2.0
  # rxdart: ^0.24.1
  dio: ^3.0.9
  intl: ^0.16.1
  http: ^0.12.1
  # hive: ^1.4.1+1
  meta: ^1.1.8
  bloc: ^4.0.0
  share: ^0.6.4+3
  vector_math: ^2.0.8
  flutter_html: ^1.0.0
  # flutter_widget_from_html: ^0.4.3
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  json_annotation: ^3.0.1
  effective_dart: ^1.2.3
  font_awesome_flutter: ^8.8.1
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  web_socket_channel: ^1.1.0
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  image: ^2.1.12
  timeago: ^2.0.26
  pattern_formatter: ^1.0.2
  google_map_location_picker: ^3.3.3
  path_provider: ^1.6.11
  flutter_native_image: ^0.0.5+2
  cached_network_image: ^2.2.0+1
  photo_view: ^0.9.2
  google_sign_in: ^4.5.1
  flutter_webview_plugin: ^0.3.11
  omise_flutter: ^0.1.2
  flutter_xlider: ^3.4.0
  flutter_svg: ^0.18.0
  # firebase_auth: ^0.16.1
  get: ^3.4.6
  form_field_validator: ^1.0.1
  keyboard_avoider: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  # hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

dependency_overrides:
  flutter_svg: ^0.18.0
#   dartx: ^0.3.0
  
flutter_icons:
  image_path: "assets/images/launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/add_product/
    - assets/images/bottom_navigation/
    - assets/images/dashboard/
    - assets/images/illustrations/
    - assets/languages/
    - assets/svg/
    - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf

        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          style: italic

        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 500
          style: italic
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic

    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

        
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore